stfalcon_tinymce:
  include_jquery: false
  tinymce_jquery: false
  language: "%locale%"
  selector: ".tinymce"
  theme:
    simple:
      content_css : "/web/css/tinymce_content.css"
      mode: "textarea"
      theme: "advanced"
      menubar: false
      statusbar: false
      plugins: "textcolor link"
      toolbar: "bold italic underline | forecolor | alignleft aligncenter alignright alignjustify | bullist numlist | link"
      theme_advanced_buttons1: "mylistbox,mysplitbutton,bold,italic,underline,separator,strikethrough,justifyleft,justifycenter,justifyright,justifyfull,bullist,numlist,undo,redo,link,unlink"
      theme_advanced_buttons2: ""
      theme_advanced_buttons3: ""
      theme_advanced_toolbar_location: "top"
      theme_advanced_toolbar_align: "left"
      theme_advanced_statusbar_location: "bottom"
    advanced:
      plugins:
        - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
        - "searchreplace wordcount visualblocks visualchars code fullscreen"
        - "insertdatetime media nonbreaking save table contextmenu directionality"
        - "emoticons template paste textcolor"
      toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
      toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
      image_advtab: true
      templates:
        - {title: 'Test template 1', content: 'Test 1'}
        - {title: 'Test template 2', content: 'Test 2'}
