version: '3.4'

volumes:
  symfony_cache:

services:
    # build stages
    php:
        build:
            context: .
            target: php_dev
        volumes:
            - ./:/var/www/symfony:delegated
            - symfony_cache:/var/www/symfony/var/cache
        environment:
            DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_DATABASE}
            PHP_IDE_CONFIG: serverName=jaimegerer
            XDEBUG_CONFIG: jaimegerer

    nginx:
        build:
            context: ./docker/nginx
            target: nginx_dev
        ports:
            - ${HOST_HTTP_PORT}:80
        volumes:
            - .:/var/www/symfony/
            - ./data/logs/nginx:/var/log/nginx

    # FROM bare images
    db:
        image: mysql:5.7
        volumes:
            - ./data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - "${HOST_PMA_HTTP_PORT}:80"
        links:
            - db
