<?php

namespace App\Entity\CRM;

use Doctrine\ORM\EntityRepository;

/**
 * RapportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RapportRepository extends EntityRepository
{
	public function custom_count($company){
		$result = $this->createQueryBuilder('r')
		->select('COUNT(r)')
		->where('r.company = :company')
		->setParameter('company', $company)
		->getQuery()
		->getSingleScalarResult();
	
		return $result;
	}
}
