imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        handler_id:  ~
        storage_id: session.storage.mock_file
        name: MOCKSESSID
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver: pdo_mysql
        dbname: 'jaime_gerer_test'
        host: 127.0.0.1
        user: root
        password: null

security:
    firewalls:
        main:
            http_basic: ~

liip_functional_test: ~

knp_snappy:
    pdf:
        enabled:    true
        binary:     C:\wkhtmltopdf\bin\wkhtmltopdf
        options: []