<?php

namespace App\Entity\Compta;

use Doctrine\ORM\EntityRepository;

/**
 * PrevTableauBordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrevTableauBordRepository extends EntityRepository
{
}
